image: python:3.6

pipelines:
    default:
        - step:
            script:
                - pip install -U tox
                - tox -e py36
    branches:
        master:
            - step:
                image: python:2.7
                script:
                    - pip install -U tox
                    - tox -e py27
    tags:
        '*':
            - step:
                script:
                    - pip install -U tox wheel
                    - tox -e py36
                    - ./deploy.bash
